In [4]:
import numpy as np

def create_1d_array():
    data = np.array([1,2,3])
    print(data)
create_1d_array()


[1 2 3]


In [5]:
def create_2d_array():
    data = np.array([[1,2,3],[4,5,6]])
    print(data)
create_2d_array()


[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

def array_operations(arr):
    """
    Perform basic array operations:
    1. Calculate mean
    2. Calculate standard deviation
    3. Find max value

    Args:
        arr (list or numpy array): Input array of numbers

    Returns:
        tuple: (mean, std_dev, max_value)
    """
    arr = np.array(arr)
    mean_value = np.mean(arr)
    std_dev = np.std(arr)
    max_value = np.max(arr)

    return mean_value, std_dev, max_value

data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
result = array_operations(data)
print("The answer is: ", result)


The answer is:  (55.0, 28.722813232690143, 100)


In [ ]:
import pandas as pd

file_path = "data/sample-data.csv"
def read_csv_file(file_path):
    data = pd.read_csv(file_path)
    return data
read_csv_file(file_path)


Name  Age  Salary          Department  Experience  \
0        Emily Johnson   28   55000           Marketing           4   
1         Michael Chen   35   72000         Engineering           8   
2      Sarah Rodriguez   42   88000               Sales          15   
3            David Kim   31   62000                  IT           6   
4      Rachel Thompson   26   48000    Customer Support           3   
5           Alex Patel   39   95000             Finance          12   
6         Jessica Wong   33   67000                  HR           7   
7         Kevin Nguyen   45  105000  Product Management          18   
8           Lisa Brown   29   58000              Design           5   
9        Robert Garcia   37   81000          Operations          11   
10          Amanda Lee   24   42000           Marketing           2   
11  Christopher Taylor   40   92000               Sales          14   
12     Olivia Martinez   27   52000    Customer Support           4   
13         Daniel Park   36   78000         Engineering           9   
14         Emma Wilson   32   65000                  IT           6   
15         Ryan Sharma   44   98000             Finance          16   
16          Sophia Liu   30   59000                  HR           5   
17     Thomas Anderson   41   87000  Product Management          13   
18      Karen Williams   25   46000              Design           3   
19       Mark Robinson   38   83000          Operations          10   
20        Jennifer Lee   33   68000           Marketing           7   
21         Andrew Chen   36   75000               Sales           8   
22       Nicole Garcia   29   54000    Customer Support           4   
23          Steven Kim   43   95000         Engineering          15   
24        Lauren Patel   27   51000                  IT           3   
25     Brian Rodriguez   39   85000             Finance          12   
26       Michelle Wong   31   62000                  HR           6   
27      Jason Thompson   34   71000  Product Management           7   
28         Rebecca Liu   26   47000              Design           2   
29     Jonathan Taylor   37   79000          Operations           9   

     Education  
0   Bachelor's  
1     Master's  
2          PhD  
3   Bachelor's  
4   Bachelor's  
5     Master's  
6   Bachelor's  
7     Master's  
8   Bachelor's  
9     Master's  
10  Bachelor's  
11         PhD  
12  Bachelor's  
13    Master's  
14  Bachelor's  
15         PhD  
16  Bachelor's  
17    Master's  
18  Bachelor's  
19    Master's  
20  Bachelor's  
21    Master's  
22  Bachelor's  
23         PhD  
24  Bachelor's  
25    Master's  
26  Bachelor's  
27  Bachelor's  
28  Bachelor's  
29    Master's

In [18]:
import pandas as pd

def handle_missing_values(df):
    print("Missing values per column:\n", df.isnull().sum())

    df = df.ffill().bfill()

    return df

file_path = "data/sample-data.csv"
df = pd.read_csv(file_path)
cleaned_df = handle_missing_values(df)
print(cleaned_df.head())


Missing values per column:
 Name          0
Age           0
Salary        0
Department    0
Experience    0
Education     0
dtype: int64
              Name  Age  Salary        Department  Experience   Education
0    Emily Johnson   28   55000         Marketing           4  Bachelor's
1     Michael Chen   35   72000       Engineering           8    Master's
2  Sarah Rodriguez   42   88000             Sales          15         PhD
3        David Kim   31   62000                IT           6  Bachelor's
4  Rachel Thompson   26   48000  Customer Support           3  Bachelor's


In [21]:
def select_data(df):
    """
    Select specific columns and rows from DataFrame
    Returns:
        pandas.DataFrame: Selected data
    """
    file_path = "data/sample-data.csv"
    df = pd.read_csv(file_path)
    data = df.loc[1:3, ['Name', 'Age', 'Experience']]
    return data
select_data(df)


Name  Age  Experience
1     Michael Chen   35           8
2  Sarah Rodriguez   42          15
3        David Kim   31           6

In [23]:
import pandas as pd

def rename_columns(df):
    """
    Rename the column 'Name' to 'Full Name' if it exists.
    
    Args:
        df (pandas.DataFrame): The input dataframe.

    Returns:
        pandas.DataFrame: DataFrame with 'Name' renamed to 'Full Name'.
    """
    df.rename(columns={'Name': 'Full Name'}, inplace=True)
    return df

file_path = "data/sample-data.csv"
df = pd.read_csv(file_path)

df = rename_columns(df)
print(df.head())


         Full Name  Age  Salary        Department  Experience   Education
0    Emily Johnson   28   55000         Marketing           4  Bachelor's
1     Michael Chen   35   72000       Engineering           8    Master's
2  Sarah Rodriguez   42   88000             Sales          15         PhD
3        David Kim   31   62000                IT           6  Bachelor's
4  Rachel Thompson   26   48000  Customer Support           3  Bachelor's
